### ISSUE TITLE
YESSSSSSSSSS the brañch gráph ís šo b€aütí₣úl

### ISSUE THREAD

**Issue by ls998** [ls998/TicTacToeFiM#1]
I know im not supposed to spam random stuff but

yayayyayyayyyyyayayayyay

i can finally edit history properly!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1

 git rebase and force push lol

important lesson in friendship: 

```
Dear Princess Celestia: egit is BAD
  Today I learned a very important lesson in friendship:
      By the way, I tried to use EGit.
      By the way, Therefore, all my git history got screwed up.
      I said "friendship and git command line interface are magic"
      By the way, Therefore, everything was fixed and harmony happened
  That's what I learned.
Your faithful student, Derpy Hooves
```

 (BTW, that letter can be compiled in [KarolS's fimpp compiler](https://github.com/KarolS/fimpp))

**Comment by Fungucide** [comment]
Your bad
